// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"context"
	"github.com/SallyKinoshita/go-rest-api/backend/internal/application/usecase"
	"github.com/SallyKinoshita/go-rest-api/backend/internal/config"
	"github.com/SallyKinoshita/go-rest-api/backend/internal/infrastructure/persistence/repository"
	"github.com/SallyKinoshita/go-rest-api/backend/internal/interfaces/controller"
	"github.com/SallyKinoshita/go-rest-api/backend/internal/middleware"
	"github.com/uptrace/bun"
)

// Injectors from wire.go:

func New(ctx context.Context, cfg *config.Config, db *bun.DB) (DI, error) {
	sampleUser := persistencerepository.NewSampleUser()
	usecaseSampleUser := usecase.NewSampleUser(db, sampleUser)
	controllerController := controller.New(usecaseSampleUser)
	clientUserAuth := persistencerepository.NewClientUserAuth()
	middlewareMiddleware := middleware.New(db, sampleUser, clientUserAuth)
	di := DI{
		Controller: controllerController,
		Middleware: middlewareMiddleware,
	}
	return di, nil
}
