services:
  sample_app:
    container_name: ${APP_NAME}
    ports:
      - "${APP_PORT}:${APP_PORT}"
      - "2345:2345"
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
      target: develop
    volumes:
      - cmd:/app/cmd
      - internal:/app/internal
      - pkg:/app/pkg
      - .air.toml:/app/.air.toml
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
    tty: true
    stdin_open: true
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      APP_NAME: ${APP_NAME}
      APP_PORT: ${APP_PORT}
      DB_DRIVER: ${DB_DRIVER}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_ENDPOINT: ${AWS_ENDPOINT}
      AWS_COGNITO_USER_POOL_ID: ${AWS_COGNITO_USER_POOL_ID}
      AWS_COGNITO_CLIENT_ID: ${AWS_COGNITO_CLIENT_ID}
      AWS_COGNITO_CLIENT_SECRET: ${AWS_COGNITO_CLIENT_SECRET}
      AWS_COGNITO_ENDPOINT: ${AWS_COGNITO_ENDPOINT}
    depends_on:
      - sample_db

  sample_db:
    container_name: ${DB_NAME}
    image: mysql:8
    command: --log-bin-trust-function-creators=1
    volumes:
      - db:/var/lib/mysql
    platform: linux/arm64
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"

  swagger_editor:
    container_name: "swagger_editor"
    image: swaggerapi/swagger-editor
    ports:
      - "${SWAGGER_EDITOR_PORT}:${APP_PORT}"
    environment:
      APP_PORT: ${APP_PORT}
      SWAGGER_EDITOR_PORT: ${SWAGGER_EDITOR_PORT}

  swagger_ui:
    container_name: "swagger_ui"
    image: swaggerapi/swagger-ui
    ports:
      - "${SWAGGER_UI_PORT}:${APP_PORT}"
    volumes:
      - ../doc/openapi.yaml:/openapi.yaml
    environment:
      SWAGGER_JSON: /openapi.yaml
      APP_PORT: ${APP_PORT}
      SWAGGER_UI_PORT: ${SWAGGER_UI_PORT}

volumes:
  db:
  cmd:
  internal:
  pkg:
