name: go

on:
  push:
    branches: [main, staging, develop]
  pull_request:
    branches:
      - "**"
    paths:
      - "backend/**"

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up actions
        uses: actions/checkout@v4

      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.3"
          check-latest: true
          cache-dependency-path: |
            ./backend/go.sum
            ./backend/go.sum

      - name: Set up library
        working-directory: ./backend
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run lint
        working-directory: ./backend
        run: staticcheck -f stylish ./...

      - name: Run test
        working-directory: ./backend
        run: go test ./... -cover
